project:
  type: website
  output-dir: docs
  resources:
    - assets/materials/**
    - assets/images/**
    - assets/docs/Lorraine-Gaudio-CV.pdf
    
website:
  title: "Lorraine Gaudio"
  site-url: "https://lorrainegaudio.github.io"

  navbar:
    title: "Lorraine Gaudio"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "AI Collaborations"
        href: human-centered-ai-collaborations.qmd
      - text: "RISE Fellowship"
        href: rise.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV & Selected Work"
        href: cv.qmd

  page-footer:
    left: "© 2026 Lorraine Gaudio | lorrainegaudio [at] boisestate [dot] edu"
    right:
      - text: "LinkedIn"
        href: "https://www.linkedin.com/in/lorraine-gaudio/"
        target: _blank
      - text: "ORCID"
        href: "https://orcid.org/0009-0000-2170-7310"
        target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    smooth-scroll: true
